### ISSUE TITLE
Validator exception in FieldsCorrectTypeRule.validate 

### ISSUE THREAD

**Issue by michaelwood** [openactive/data-model-validator#353]
We're seeing an issue on conformance-services where the validator appears to unexpectedly throw this exception. We're catching it but I'm not confident at the moment that the validator or conformance-services isn't in a strange state afterwards (currently investigating this).

```
2020-08-11T11:20:48.245531+00:00 app[worker.1]: at encodeURIComponent (<anonymous>)
2020-08-11T11:20:48.245531+00:00 app[worker.1]: at Object.encode (/app/node_modules/uritemplate/bin/uritemplate.js:148:29)
2020-08-11T11:20:48.245532+00:00 app[worker.1]: at Object.encodeCharacter (/app/node_modules/uritemplate/bin/uritemplate.js:179:27)
2020-08-11T11:20:48.245532+00:00 app[worker.1]: at Object.encodeLiteral (/app/node_modules/uritemplate/bin/uritemplate.js:346:111)
2020-08-11T11:20:48.245533+00:00 app[worker.1]: at new LiteralExpression (/app/node_modules/uritemplate/bin/uritemplate.js:439:39)
2020-08-11T11:20:48.245533+00:00 app[worker.1]: at Function.parse (/app/node_modules/uritemplate/bin/uritemplate.js:615:30)
2020-08-11T11:20:48.245534+00:00 app[worker.1]: at Field.detectType (/app/node_modules/@openactive/data-model-validator/src/classes/field.js:165:40)
2020-08-11T11:20:48.245536+00:00 app[worker.1]: at FieldsCorrectTypeRule.validateField (/app/node_modules/@openactive/data-model-validator/src/rules/core/fields-correct-type-rule.js:209:34)
2020-08-11T11:20:48.245537+00:00 app[worker.1]: at FieldsCorrectTypeRule.validate (/app/node_modules/@openactive/data-model-validator/src/rules/rule.js:34:40)
```

**Comment by michaelwood** [comment]
Example from some live data causing an [exception](https://validator.openactive.io/?version=2.0&validationMode=RPDEFeed#/json/ewogICJAaWQiOiAiaHR0cHM6Ly9ib29rd2hlbi5jb20vYXBpL29wZW5hY3RpdmUvc2Vzc2lvbnNlcmllcy90azV5a3hvazhjaWMiLAogICJ1cmwiOiAiaHR0cHM6Ly9ib29rd2hlbi5jb20vYW5uc3lvZ2Fsb3VuZ2U_cj1vYSIsCiAgIm5hbWUiOiAi8J-YtCBTVU5EQVkgUmVsYXggYW5kIFJlY2hhcmdlIFJlc3RvcmF0aXZlIFlvZ2EgLSBTVFVESU8gcGxhY2VzIPCfj6EiLAogICJAdHlwZSI6ICJTZXNzaW9uU2VyaWVzIiwKICAiaW1hZ2UiOiBbCiAgICB7CiAgICAgICJ1cmwiOiAiaHR0cHM6Ly9ia3duLnMzLmFtYXpvbmF3cy5jb20vYXR0YWNobWVudHMvaDF4bW16NHRyaWM1L3JxY2c5b2Z3eGRiaS9wcm9jZXNzZWQvd3cyZjJmOHFybmx0L2FsdF9yYXRpb18xNng5XzF4XzUxREQ2RjJELTZBODgtNDU0My04QjBBLUI2RjhDMDkwQ0MyMy5qcGVnIiwKICAgICAgIkB0eXBlIjogIkltYWdlT2JqZWN0IgogICAgfSwKICAgIHsKICAgICAgInVybCI6ICJodHRwczovL2Jrd24uczMuYW1hem9uYXdzLmNvbS9hdHRhY2htZW50cy9oMXhtbXo0dHJpYzUvcnFjZzlvZnd4ZGJpL3Byb2Nlc3NlZC93dzJmMmY4cXJubHQvYWx0X3JhdGlvXzR4M18xeF81MURENkYyRC02QTg4LTQ1NDMtOEIwQS1CNkY4QzA5MENDMjMuanBlZyIsCiAgICAgICJAdHlwZSI6ICJJbWFnZU9iamVjdCIKICAgIH0sCiAgICB7CiAgICAgICJ1cmwiOiAiaHR0cHM6Ly9ia3duLnMzLmFtYXpvbmF3cy5jb20vYXR0YWNobWVudHMvaDF4bW16NHRyaWM1L3JxY2c5b2Z3eGRiaS9wcm9jZXNzZWQvd3cyZjJmOHFybmx0L2FsdF9yYXRpb18xeDFfMXhfNTFERDZGMkQtNkE4OC00NTQzLThCMEEtQjZGOEMwOTBDQzIzLmpwZWciLAogICAgICAiQHR5cGUiOiAiSW1hZ2VPYmplY3QiCiAgICB9CiAgXSwKICAib2ZmZXJzIjogWwogICAgewogICAgICAibmFtZSI6ICJTaW5nbGUgY2xhc3MgdGlja2V0IiwKICAgICAgIkB0eXBlIjogIk9mZmVyIiwKICAgICAgInByaWNlIjogIjguMDAiLAogICAgICAiZGVzY3JpcHRpb24iOiAiUGxlYXNlIGJyaW5nIGNhc2ggb24gdGhlIGRheSBvciBwYXkgb25saW5lLiAgV2h5IG5vdCBtYWtlIGEgc2F2aW5nIGFuZCBwdXJjaGFzZSB3aXRoIGEgY2xhc3MgcGFzcy5cclxuWW91IGNhbiBhbHNvIHRyYW5zZmVyIHBheW1lbnQgdG8gdGhlIGZvbGxvd2luZyBhY2NvdW50IGlmIHlvdSBwcmVmZXJcclxuTXJzIEFubiBSaWRkZWxsXHJcbjIwLTM0LTYwXHJcbjYzNjk1OTA1ICIsCiAgICAgICJwcmljZUN1cnJlbmN5IjogIkdCUCIKICAgIH0KICBdLAogICJAY29udGV4dCI6IFsKICAgICJodHRwczovL29wZW5hY3RpdmUuaW8vIiwKICAgICJodHRwczovL29wZW5hY3RpdmUuaW8vbnMtYmV0YSIKICBdLAogICJhY3Rpdml0eSI6IFsKICAgIHsKICAgICAgIkBpZCI6ICJodHRwczovL29wZW5hY3RpdmUuaW8vYWN0aXZpdHktbGlzdCMxYjdkNmE4OS0xZjZiLTRlM2QtODljOS1jMzJmYzUzOWE3ZGQiLAogICAgICAiQHR5cGUiOiAiQ29uY2VwdCIsCiAgICAgICJpblNjaGVtZSI6ICJodHRwczovL29wZW5hY3RpdmUuaW8vYWN0aXZpdHktbGlzdCIsCiAgICAgICJwcmVmTGFiZWwiOiAiUmVzdG9yYXRpdmUgWW9nYSIKICAgIH0KICBdLAogICJsb2NhdGlvbiI6IHsKICAgICJAaWQiOiAiaHR0cHM6Ly9ib29rd2hlbi5jb20vYXBpL29wZW5hY3RpdmUvbG9jYXRpb25zL21qMncybWN6MDZ4ZyIsCiAgICAiZ2VvIjogewogICAgICAidHlwZSI6ICJHZW9Db29yZGluYXRlcyIsCiAgICAgICJsYXRpdHVkZSI6IDUyLjk4MjgxMTYsCiAgICAgICJsb25naXR1ZGUiOiAtMC4yOTU0MjI2CiAgICB9LAogICAgIkB0eXBlIjogIlBsYWNlIiwKICAgICJhZGRyZXNzIjogIkFubuKAmXMgWW9nYSBMb3VuZ2VcbjQgSGFsbCBDbG9zZVxuSGVja2luZ3RvblxuU2xlYWZvcmRcbkxpbmNzXG5ORzM0IDlTRiIsCiAgICAiZGVzY3JpcHRpb24iOiAiIgogIH0sCiAgIm9yZ2FuaXplciI6IHsKICAgICJAaWQiOiAiaHR0cHM6Ly9ib29rd2hlbi5jb20vYXBpL29wZW5hY3RpdmUvb3JnYW5pemVycy9oMXhtbXo0dHJpYzUiLAogICAgInVybCI6ICJodHRwOi8vd3d3LmFubnN5b2dhbG91bmdlLmNvbSIsCiAgICAibmFtZSI6ICJBbm7igJlzIFlvZ2EgTG91bmdlICIsCiAgICAiQHR5cGUiOiAiT3JnYW5pemF0aW9uIiwKICAgICJlbWFpbCI6ICJBbm5zeW9nYWxvdW5nZUBnbWFpbC5jb20iLAogICAgInRlbGVwaG9uZSI6ICIwNzUzNSA3MTM0NjciCiAgfSwKICAiZGVzY3JpcHRpb24iOiAiQ2hpbGxlZCBvdXQgeW9nYSBzZXNzaW9uLCB2ZXJ5IHJlc3RvcmF0aXZlIGFuZCBhIHBlcmZlY3Qgd2F5IHRvIHByZXBhcmUgZm9yIGEgYnVzeSB3ZWVrLiBTbG93IGRvd24sIGJyZWF0aGUgYW5kIHNwZW5kIHNvbWUgdGltZSBmb3IgeW91cnNlbGYuIFF1aWV0IGFuZCBtZWRpdGF0aXZlIGZsb29yLWJhc2VkIFlpbiBhbmQgcmVzdG9yYXRpdmUsIHN1cHBvcnRlZCBwb3N0dXJlcyBzdWl0YWJsZSBmb3IgYWxsIGFnZXMgYW5kIGFiaWxpdGllcyBldmVuIHRob3NlIG5ldyB0byBZb2dhLiBJbiB0aGlzIHNtYWxsLCBmcmllbmRseSBjbGFzcyBldmVyeW9uZSBpcyBpbnZpdGVkIHRvIGxpc3RlbiB0byB0aGVpciBvd24gdW5pcXVlIGJvZHkgYW5kIGFkYXB0IHBvc2VzIHRvIHN1aXQgdGhlbSAocGFydGljdWxhcmx5IGlmIGNhcnJ5aW5nIGFuIGluanVyeSkgb3Igc2ltcGx5IHJlc3QuIExvbmdlci1oZWxkIHN0cmV0Y2hlcyBwcm9tb3RlIHRoZSBmbG93IG9mIGhlYWx0aHkgY2hpIChlbmVyZ3kpIGFyb3VuZCB0aGUgYm9keSwgbm91cmlzaGluZyB5b3VyIGpvaW50cyBhbmQgY29ubmVjdGl2ZSB0aXNzdWUuIFBoeXNpY2FsbHkgaW5jcmVhc2UgeW91ciByYW5nZSBvZiBtb3ZlbWVudCB3aGlsc3QgZm9jdXNzaW5nIG9uIHlvdXJzZWxmIGFuZCB0aGUgcHJlc2VudCBtb21lbnQuIFRoZSBjbGFzcyBpcyBhY2NvbXBhbmllZCBieSBnZW50bGUgbXVzaWMsIHBvZXRyeSBhbmQgcGhpbG9zb3BoeSBhbmQgaXMgZGVzaWduZWQgdG8gaGVscCB5b3UgcmVsYXgsIGltcHJvdmUgZmxleGliaWxpdHkgYW5kIHJlY2hhcmdlIHRob3NlIGJhdHRlcmllcyByZWFkeSBmb3IgdGhlIHdlZWsgYWhlYWQuIFRoZSBjbGFzcyBydW5zIGZvciBhIGdlbmVyb3VzIDc1IG1pbnMgdG8gZW5hYmxlIHlvdSB0byBzZXR0bGUgYXQgdGhlIHN0YXJ0IG9mIHRoZSBwcmFjdGljZSwgZnVsbHkgcmVsYXggYW5kIGVuZCBpbiBhIGNoaWxsZWQgc2F2YXNhbmEuIEhvcGVmdWxseSB5b3Ugd2lsbCBsZWF2ZSB3aXRoIGEgc2Vuc2Ugb2Ygam95IGFuZCBjb25uZWN0aW9uIHRvIHlvdXJzZWxmIGFuZCBvdGhlcnMsIG5pY2VseSBzdHJldGNoZWQgYW5kIHJlbGF4ZWQuIiwKICAiZXZlbnRTY2hlZHVsZSI6IFsKICAgIHsKICAgICAgIkB0eXBlIjogIlNjaGVkdWxlIiwKICAgICAgImJ5RGF5IjogWwogICAgICAgIFsKICAgICAgICAgICJodHRwczovL3NjaGVtYS5vcmcvU3VuZGF5IgogICAgICAgIF0KICAgICAgXSwKICAgICAgImVuZERhdGUiOiAiMjAyMC0wOS0wMSIsCiAgICAgICJlbmRUaW1lIjogIjE1OjE1OjAwIiwKICAgICAgImR1cmF0aW9uIjogIlBUMUgxNU0iLAogICAgICAic3RhcnREYXRlIjogIjIwMjAtMDgtMDIiLAogICAgICAic3RhcnRUaW1lIjogIjE0OjAwOjAwIiwKICAgICAgImlkVGVtcGxhdGUiOiAiaHR0cHM6Ly9ib29rd2hlbi5jb20vYXBpL29wZW5hY3RpdmUvc2NoZWR1bGVkc2Vzc2lvbnMvdGs1eWt4b2s4Y2ljX3tzdGFydERhdGV9IiwKICAgICAgInJlcGVhdENvdW50IjogMywKICAgICAgInVybFRlbXBsYXRlIjogImh0dHBzOi8vYm9va3doZW4uY29tL2FwaS9vcGVuYWN0aXZlL3NjaGVkdWxlcy9hbm5zeW9nYWxvdW5nZS9zbngxL3tzdGFydERhdGV9IiwKICAgICAgInJlcGVhdEZyZXF1ZW5jeSI6ICJQMlciLAogICAgICAic2NoZWR1bGVUaW1lem9uZSI6ICJFdXJvcGUvTG9uZG9uIiwKICAgICAgInNjaGVkdWxlZEV2ZW50VHlwZSI6ICJTY2hlZHVsZWRTZXNzaW9uIgogICAgfQogIF0sCiAgImdlbmRlclJlc3RyaWN0aW9uIjogImh0dHBzOi8vb3BlbmFjdGl2ZS5pby9Ob1Jlc3RyaWN0aW9uIiwKICAiZXZlbnRBdHRlbmRhbmNlTW9kZSI6ICJodHRwczovL3NjaGVtYS5vcmcvT2ZmbGluZUV2ZW50QXR0ZW5kYW5jZU1vZGUiLAogICJhdHRlbmRlZUluc3RydWN0aW9ucyI6ICJDb3JvbmF2aXJ1cyAoQ09WSUQtMTkpXHJcbuKAi1xyXG5QbGVhc2UgYmUgYXNzdXJlZCB0aGF0IGV2ZXJ5b25lJ3Mgd2VsbGJlaW5nIGFuZCBzYWZldHkgaXMgYSB0b3AgcHJpb3JpdHkgZm9yIHVzLiAgXHJcbuKAi1xyXG5DbGFzcyBzaXplcyBoYXZlIGJlZW4gcmVkdWNlZCB0byBhZGhlcmUgdG8gc29jaWFsIGRpc3RhbmNpbmcgZ3VpZGVsaW5lcy4gIFRoZSBzdHVkaW8gYW5kIHdob2xlIHByZW1pc2VzIGFyZSBjbGVhbmVkIHJlZ3VsYXJseSB3aXRoIGhpZ2ggdG91Y2ggYXJlYXMgc2FuaXRpc2VkIGJlZm9yZSBhbmQgYWZ0ZXIgZXZlcnkgY2xhc3MuICBUaGVyZSBhcmUgd2Vla2x5IHByb2Zlc3Npb25hbCBjbGVhbnMuICBXZSBoYXZlIHRha2VuIHRoZSBkZWNpc2lvbiB0byByZWR1Y2UgdGhlIHVzZSBvZiBwcm9wcyBpbiBvdXIgY2xhc3NlcyBmb3IgdGhlIHRpbWUgYmVpbmcgc28gcGxlYXNlIGJyaW5nIGFsb25nIHlvdXIgb3duIGVxdWlwbWVudCBpZiB5b3UgaGF2ZSBpdC5cclxuUGxlYXNlIGhlbHAgdXMga2VlcCBUaGUgWW9nYSBMb3VuZ2UgYXMgc2FmZSBhbmQgaHlnaWVuaWMgYXMgcG9zc2libGUgYnkgd2FzaGluZyB5b3VyIGhhbmRzIGJlZm9yZSBjbGFzcyAob3VyIGJhdGhyb29tcyBhbmQgc3R1ZGlvIGluY2x1ZGUgaGFuZCBzYW5pdGlzZXIpLiAgXHJcbuKAi1xyXG5Nb3N0IHN0dWRlbnRzIHByZXBheSBmb3IgY2xhc3NlcyB0aHJvdWdoIFN0cmlwZSBvciBiYW5rIHRyYW5zZmVyLCAgYnV0IGFzIGFuIGFkZGl0aW9uYWwgcHJlY2F1dGlvbiB0byBoZWxwIHByZXZlbnQgdGhlIHNwcmVhZCBvZiBDb3JvbmF2aXJ1cywgd2UgYXJlIGVuY291cmFnaW5nIHlvdSB0byBjb25zaWRlciBjYXNobGVzcyB0cmFuc2FjdGlvbnMgaWYgYXQgYWxsIHBvc3NpYmxlLlxyXG7igItcclxuSWYgeW91IGFyZSBub3QgZmVlbGluZyB3ZWxsLCBwbGVhc2Ugc3RheSBhdCBob21lIGFuZCByZXN0LiAgQWxzbyBkbyBiZSBtaW5kZnVsIG9mIHRoZSBsYXRlc3QgRm9yZWlnbiBPZmZpY2UgYWR2aWNlIGFib3V0IHRyYXZlbC4gIElmIHlvdSBoYXZlIGJlZW4gYWJyb2FkLCBjaGVjayB3aGF0IHRoZXkgaGF2ZSB0byBzYXkgYWJvdXQgc2VsZiBpc29sYXRpb24gYW5kIG90aGVyIHByZWNhdXRpb25zLlxyXG5cclxuUmVtZW1iZXIgeW91IGNhbiBjYW5jZWwgY2xhc3NlcyB2aWEgeW91ciBlbWFpbCBjbGFzcyBjb25maXJtYXRpb24gb3IgcmVtaW5kZXIgZW1haWwgdXAgdG8gMjQgaG91cnMgYmVmb3JlIHRoZSBzdGFydCBvZiBjbGFzcyB3aXRob3V0IHBlbmFsdHkuXHJcbuKAi1xyXG5UaGFuayB5b3Ugc28gbXVjaCBmb3IgeW91ciBjb250aW51ZWQgc3VwcG9ydCBhbmQgY2FyZS4gIFxyXG5NYXkgd2UgYmUgaGFwcHksIG1heSB3ZSBiZSBoZWFsdGh5LlxyXG7igIsiLAogICJtYXhpbXVtQXR0ZW5kZWVDYXBhY2l0eSI6IDQsCiAgImJldGE6Zm9ybWF0dGVkRGVzY3JpcHRpb24iOiAiPHA-Q2hpbGxlZCBvdXQgeW9nYSBzZXNzaW9uLCB2ZXJ5IHJlc3RvcmF0aXZlIGFuZCBhIHBlcmZlY3Qgd2F5IHRvIHByZXBhcmUgZm9yIGEgYnVzeSB3ZWVrLiBTbG93IGRvd24sIGJyZWF0aGUgYW5kIHNwZW5kIHNvbWUgdGltZSBmb3IgeW91cnNlbGYuPC9wPlxuXG48cD5RdWlldCBhbmQgbWVkaXRhdGl2ZSBmbG9vci1iYXNlZCBZaW4gYW5kIHJlc3RvcmF0aXZlLCBzdXBwb3J0ZWQgcG9zdHVyZXMgc3VpdGFibGUgZm9yIGFsbCBhZ2VzIGFuZCBhYmlsaXRpZXMgZXZlbiB0aG9zZSBuZXcgdG8gWW9nYS4gIEluIHRoaXMgc21hbGwsIGZyaWVuZGx5IGNsYXNzIGV2ZXJ5b25lIGlzIGludml0ZWQgdG8gbGlzdGVuIHRvIHRoZWlyIG93biB1bmlxdWUgYm9keSBhbmQgYWRhcHQgcG9zZXMgdG8gc3VpdCB0aGVtIChwYXJ0aWN1bGFybHkgaWYgY2FycnlpbmcgYW4gaW5qdXJ5KSBvciBzaW1wbHkgcmVzdC48L3A-XG5cbjxwPkxvbmdlci1oZWxkIHN0cmV0Y2hlcyBwcm9tb3RlIHRoZSBmbG93IG9mIGhlYWx0aHkgY2hpIChlbmVyZ3kpIGFyb3VuZCB0aGUgYm9keSwgbm91cmlzaGluZyB5b3VyIGpvaW50cyBhbmQgY29ubmVjdGl2ZSB0aXNzdWUuIFBoeXNpY2FsbHkgaW5jcmVhc2UgeW91ciByYW5nZSBvZiBtb3ZlbWVudCB3aGlsc3QgZm9jdXNzaW5nIG9uIHlvdXJzZWxmIGFuZCB0aGUgcHJlc2VudCBtb21lbnQuPGJyPlxuVGhlIGNsYXNzIGlzIGFjY29tcGFuaWVkIGJ5IGdlbnRsZSBtdXNpYywgcG9ldHJ5IGFuZCBwaGlsb3NvcGh5IGFuZCBpcyBkZXNpZ25lZCB0byBoZWxwIHlvdSByZWxheCwgaW1wcm92ZSBmbGV4aWJpbGl0eSBhbmQgcmVjaGFyZ2UgdGhvc2UgYmF0dGVyaWVzIHJlYWR5IGZvciB0aGUgd2VlayBhaGVhZC4gPC9wPlxuXG48cD5UaGUgY2xhc3MgcnVucyBmb3IgYSBnZW5lcm91cyA3NSBtaW5zIHRvIGVuYWJsZSB5b3UgdG8gc2V0dGxlIGF0IHRoZSBzdGFydCBvZiB0aGUgcHJhY3RpY2UsIGZ1bGx5IHJlbGF4IGFuZCBlbmQgaW4gYSBjaGlsbGVkIHNhdmFzYW5hLiBIb3BlZnVsbHkgeW91IHdpbGwgbGVhdmUgd2l0aCBhIHNlbnNlIG9mIGpveSBhbmQgY29ubmVjdGlvbiB0byB5b3Vyc2VsZiBhbmQgb3RoZXJzLCBuaWNlbHkgc3RyZXRjaGVkIGFuZCByZWxheGVkLiA8L3A-XG4iCn0)
